# Generated by Django 3.2.23 on 2023-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Store', '0010_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('TV', 'TV'), ('Screens', 'Screens'), ('Speakers', 'Speakers'), ('Laptops', 'Laptops'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
